"""crear tabla transacciones ledger

Revision ID: 19615ed21e97
Revises: 529303d8e306
Create Date: 2026-09-13 19:27:50.928793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19615ed21e97'
down_revision = '529303d8e306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacciones_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billetera_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('subasta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['billetera_id'], ['billeteras.id'], ),
    sa.ForeignKeyConstraint(['subasta_id'], ['subastas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacciones_ledger')
    # ### end Alembic commands ###
