"""crear tabla billeteras

Revision ID: 212343855f5c
Revises: 845bf8b3ab60
Create Date: 2026-09-13 19:24:18.774693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212343855f5c'
down_revision = '845bf8b3ab60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billeteras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('saldo_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_retenido', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_disponible', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billeteras')
    # ### end Alembic commands ###
