"""crear tabla pujas

Revision ID: 529303d8e306
Revises: 47b0bf4307e8
Create Date: 2026-09-13 19:26:44.778593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529303d8e306'
down_revision = '47b0bf4307e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pujas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subasta_id', sa.Integer(), nullable=False),
    sa.Column('comprador_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_puja', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comprador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['subasta_id'], ['subastas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pujas')
    # ### end Alembic commands ###
