"""crear tabla auditoria logs

Revision ID: 6c89c5da892c
Revises: 19615ed21e97
Create Date: 2026-09-13 19:28:50.506662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c89c5da892c'
down_revision = '19615ed21e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('detalle_json', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditoria_logs')
    # ### end Alembic commands ###
