"""crear tabla usuarios

Revision ID: 845bf8b3ab60
Revises: 75b9d679e480
Create Date: 2026-09-13 19:20:06.617613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845bf8b3ab60'
down_revision = '75b9d679e480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
